### PR TITLE
Fix check-formatting.sh

### PR DESCRIPTION
**Pull request by senekor**
I guess this broke because the format of pnpm-lock.yaml changed. I hope getting the info from the pnpm CLI is more stable.

### CODE REVIEW

**Comment by senekor** [comment]
Aah, `pnpm` is not available in that script. Gotta find another way.

**Comment by senekor** [comment]
@ErikSchierboom I think it should work now

**Comment by ErikSchierboom** [comment]
Looks like it still fails

**Comment by senekor** [comment]
@ErikSchierboom it shows me that all checks passed, including format :thinking:

**Comment by ErikSchierboom** [comment]
Must have been a caching thing of the gh app 🤷‍♂️

**Comment by ErikSchierboom** [comment]
Thanks a ton for these two PRs!

**Comment by senekor** [comment]
No problem :)

**Pull request merged**
