### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@SleeplessByte dependabot keeps sending PRs to update things. This PR is an attempt to update the dependencies, but it appears that breaks things. Any idea?

**Comment by SleeplessByte** [comment]
What does it break? It shows all green on my phone

**Comment by ErikSchierboom** [comment]
I'll be d*mned. I swear it didn't pass the tests 🤷

**Comment by SleeplessByte** [comment]
This is good right?

**Comment by ErikSchierboom** [comment]
Yes, that looks good

**Pull request merged**
